name: Playwright Behave CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # ---------------- Checkout code ----------------
    - name: Checkout code
      uses: actions/checkout@v3

    # ---------------- Setup Python ----------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # ---------------- Install dependencies ----------------
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    # ---------------- Run Behave BDD tests ----------------
    - name: Run Behave BDD tests
      run: |
        source venv/bin/activate
        mkdir -p PythonPlaywright/reports
        python PythonPlaywright/Tests/test_runner.py

    # ---------------- Combine HTML reports (Optional) ----------------
    - name: Combine HTML reports
      run: |
        source venv/bin/activate
        python PythonPlaywright/combine_html_reports.py

    # ---------------- Upload Combined Report ----------------
    - name: Upload Combined HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: combined-html-report
        path: PythonPlaywright/reports/combined_report.html

    # ---------------- Upload Individual Feature Reports ----------------
    - name: Upload Individual Feature Reports
      uses: actions/upload-artifact@v4
      with:
        name: feature-html-reports
        path: PythonPlaywright/reports/*.html
