name: Playwright Behave CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python -m playwright install

    - name: Run Behave BDD tests
      run: |
        source venv/bin/activate
        python Tests/test_runner.py

    - name: Combine HTML reports
      run: |
        source venv/bin/activate
        python combine_html_reports.py

    - name: Upload Combined HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: combined-html-report
        path: reports/combined_report.html

    - name: Upload Individual Feature Reports
      uses: actions/upload-artifact@v4
      with:
        name: feature-html-reports
        path: reports/*.html
